train_name: whisper
audio_max_length: 160000 # 10s
text_max_length: 300
accelerator: auto
weight_decay: 0.01
adam_epsilon: 1.0e-8
num_worker: 1
validate_every_n_batches: 1000
num_devices: 1

model_name: small
learning_rate: 1.25e-5 # small
batch_size: 4 
num_train_steps: 225000
warmup_steps: 1000
gradient_accumulation_steps: 1

monitor: 'val_noisy_multi_babble/acc' # noisy test set
noise_prob: 1.0
noise_fn: '/data/sls/scratch/roudi/datasets/musan/tsv/all/train.tsv'

# need modify
noise_fn_val: 'E:/dataset/noise/babble/muavic/valid.tsv' # single lrs3 babble mixture
noise_fn_test: 'E:/dataset/noise/babble/muavic/test.tsv' # single lrs3 babble mixture

spec_augment: ""
dropout_rate: 0 


lang: ar
vc2: False
vc2_path: ''
muavic_root: 'E:/dataset/'
resume_training: false

train_id: whisper_en-x_small

log_output_dir: "slurm/train_audio_slurm"
check_output_dir: "models/checkpoint"